spring:
  application:
    name: bus-ticketing-system-api

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver


  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml # Path to your master changelog file
    enabled: true
    default-schema: bus_db


  jpa:
    hibernate:
      ddl-auto: none
      default_schema: bus_db
    show-sql: true


springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api

server:
  port: 8085
